### ISSUE TITLE
windows环境下文件路径格式显示错误

### ISSUE THREAD

**Issue by zainmiku** [yaocccc/nvim-lines.lua#2]
如图
<img width="1031" alt="屏幕截图 2023-03-09 204028" src="https://user-images.githubusercontent.com/43474068/224026053-035c7830-856d-4d59-bd82-992082715896.png">

**Comment by yaocccc** [comment]
好的，明天上班看一下

**Comment by yaocccc** [comment]
lua print(vim.api.nvim_eval("expand('%:p')"))
你好，麻烦执行一下这个看看结果

**Comment by yaocccc** [comment]
可以尝试更新校验

**Comment by zainmiku** [comment]
已解决,感谢
